site_name: GPIO One
theme: readthedocs
site_url: http://pythonhosted.org/gpioone
repo_url: https://github.com/cymplecy/python-gpioone
site_description: A simple interface to everyday GPIO components used with Raspberry Pi
site_author: Simon Walters
site_dir: pythonhosted
google_analytics: ['UA-46270871-6', 'pythonhosted.org/gpioone']
pages:
- 'Home': 'index.md'
- 'Input Devices': 'inputs.md'
- 'Output Devices': 'outputs.md'
- 'Boards and Accessories': 'boards.md'
- 'Notes': 'notes.md'
- 'Recipes': 'recipes.md'
